name: 'test apply'

on:
  push:
    branches:
      - main

env:
  BRANCH: abc
jobs:
  test-job:
    runs-on: ubuntu-latest
    name: "extract branch name"
    steps:
      - name: abc
        run: |
          echo ${{ BRANCH_NAME }}
          echo ${{ github.ref.name }}