name: 'test apply'

on:
  pull_request:
    branches:
      - main

env:
  BRANCH: abc
jobs:
  test-job:
    runs-on: ubuntu-latest
    name: "extract branch name"
    steps:
      - name: abc
        run: |
          echo ${{ github.ref.name }}
          echo ${{ github.ref }}
          echo ${{ github.ref.protected }}
          echo ${{ github.job }}
          echo ${{ github.head.ref }}
          echo ${{ github.action }}
