name: 'test apply'

on:
  push:
    branches:
      - main

env:
  BRANCH: abc
jobs:
  test-job:
    name: "extract branch name"
    steps:
      - name: abc
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref.name }}