name: 'test apply'

on:
  pull_request:
    branches:
      - main

env:
  BRANCH: abc
jobs:
  test-job:
    runs-on: ubuntu-latest
    name: "extract branch name"
    steps:
      - name: abc
        run: |
          echo ${{ github.ref.name }}
          echo ${{ ${GITHUB_REF#refs/heads/} }}